language: php

sudo: required

notifications:
  email:
    - contato@thizer.com

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  global:
    - DEVELOPMENT=true
    - SHOW_ERRORS=true

    - TRAVIS=true

matrix:
  fast_finish: true
  allow_failures:
      - php: hhvm

before_script:
  - php composer.phar install
  - git config --global user.name thizerdev
  - git config --global user.email thizerdev@gmail.com

script:
  - mkdir -p var/log
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'