<h1>Acompanhe nosso trabalho</h1>

<div class="row">
  <div class="col-9">
    <p>
      Aqui você encontra diversos conteúdos que
      criamos especialmente para você!
    </p>
  </div>
  <div class="col-3">
    <ul>
      <?php foreach ($menus['03.blog'] as $url => $title): ?>
        <li><a href="<?php echo $url; ?>" title="<?php echo $title; ?>"><?php echo $title; ?></a></li>
      <?php endforeach; ?>
    </ul>
  </div>
</div>
