<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?php echo $uri->url('/assets/dist/css/bootstrap.min.css'); ?>">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?php echo $uri->url('/assets/dist/vendor/fontawesome-free/css/all.min.css'); ?>">

    <!-- trace font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">

    <title>Something went wrong!</title>
  </head>
  <body class="bg-dark">
    <div class="container">
  
      <h1 class="text-white mt-5" style="font-size: 48pt;">
        <?php if($exception->getCode()): ?>
          <i class="text-warning">
            #<?php echo $exception->getCode(); ?><i class="fa fa-exclamation"></i>
          </i>
          - <?php echo str_maxlen($exception->getMessage(), 28); ?>
        <?php else: ?>
          <i class="text-warning">
            #Error <i class="fa fa-exclamation"></i>
          </i>
          - Something went wrong
        <?php endif; ?>
      </h1>
      <div class="card card-light mb-5">
        <div class="card-body">
          Something went wrong and your request could not be retrieved.
          <br/>
          What about <a href="/">to go back to the home page</a> and start all over again?
        </div>
      </div>
      
      <?php if ($showErrors): ?>
      <hr/>
      <div class="row">
        <div class="col-sm-12">
          <h3 class="text-warning"><i class="fa fa-bars"></i> Error Stack Trace</h3>
          
          <table class="table bg-light text-secondary">
            <thead class="bg-dark text-light font-weight-bold">
              <tr>
                <td>Message:</td>
                <td><?php echo $exception->getMessage(); ?></td>
              </tr>
            </thead>
            <tbody style="font-family: 'Roboto Mono', monospace; font-size: 9pt;">
              <tr>
                <td>File:</td>
                <td class="font-weight-bold"><?php echo $exception->getFile(); ?>::(<?php echo $exception->getLine(); ?>)</td>
              </tr>
              <?php if ($exception->getTrace()): ?>
                <tr>
                  <td>Stack Trace:</td>
                  <td>
                    <?php foreach ($exception->getTrace() as $key => $trace): ?>
                      <div class="card mb-1" style="background-color: rgba(0,0,0,.05);">
                        <div class="card-body">
                          #<?php echo $key + 1; ?> - File: <?php echo $trace['file'] ?? '[internal function]'; ?><?php echo isset($trace['line']) ? "::({$trace['line']})" : ''; ?>
                          <br />
                          <?php if ($trace['args']): ?>
                            <?php echo $trace['class'] ?? ''; ?><?php echo $trace['type'] ?? ''; ?><?php echo $trace['function']; ?>(<?php echo getTraceArgsAsString($trace['args']); ?>);
                          <?php else: ?>
                            <?php echo $trace['class'] ?? ''; ?><?php echo $trace['type'] ?? ''; ?><?php echo $trace['function']; ?>();
                          <?php endif; ?>
                        </div>
                      </div>
                    <?php endforeach; ?>
                  </td>
                </tr>
              <?php endif; ?>
              <tr>
                <td>Exception String:</td>
                <td>
                  <div class="card mb-1" style="background-color: rgba(0,0,0,.05);">
                    <div class="card-body">
                      <?php echo nl2br($exception->__toString()); ?>
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <?php endif; ?>
    </div>
    
  </body>
</html>